### ISSUE TITLE
Latest discord update fucked it in the ass

### ISSUE THREAD

**Issue by solonovamax** [cainy-a/ServerColumns-PowercordFix#6]
![image](https://user-images.githubusercontent.com/46940694/136556314-bc9b90bc-8b19-4e1d-837e-192eb1b7e5c4.png)

Gonna probably fix it later today or tomorrow when I get time.

**Comment by yellowsink** [comment]
Mkay
________________________________
From: solo ***@***.***>
Sent: Friday, October 8, 2021 1:25:20 PM
To: yellowsink/ServerColumns-PowercordFix ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yellowsink/ServerColumns-PowercordFix] Latest discord update fucked it in the ass (#6)


[image]<https://user-images.githubusercontent.com/46940694/136556314-bc9b90bc-8b19-4e1d-837e-192eb1b7e5c4.png>

Gonna probably fix it later today or tomorrow when I get time.
